### ISSUE TITLE
[CORALFetch] EventEmitter memory leak

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/ezs#248]
```
(node:79571) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 16 abort listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:601:17)
    at EventEmitter.addListener (node:events:619:10)
    at AbortSignal.addEventListener (/home/thouveni/devel/ezs/packages/conditor/node_modules/node-abort-controller/index.js:19:23)
    at /home/thouveni/devel/ezs/packages/conditor/node_modules/fetch-with-proxy/node_modules/node-fetch/lib/index.js:1472:11
    at new Promise (<anonymous>)
    at fetch (/home/thouveni/devel/ezs/packages/conditor/node_modules/fetch-with-proxy/node_modules/node-fetch/lib/index.js:1437:9)
    at fetch (/home/thouveni/devel/ezs/packages/conditor/node_modules/fetch-with-proxy/lib/index.js:123:36)
    at /home/thouveni/devel/ezs/packages/conditor/lib/corhal-fetch.js:22:54
    at RetryOperation.runAttempt [as _fn] (/home/thouveni/devel/ezs/packages/conditor/node_modules/async-retry/lib/index.js:42:15)
    at RetryOperation.attempt (/home/thouveni/devel/ezs/packages/conditor/node_modules/retry/lib/retry_operation.js:116:8)
    at run (/home/thouveni/devel/ezs/packages/conditor/node_modules/async-retry/lib/index.js:55:8)
    at new Promise (<anonymous>)
    at retry (/home/thouveni/devel/ezs/packages/conditor/node_modules/async-retry/lib/index.js:58:10)
    at Object.CORHALFetch (/home/thouveni/devel/ezs/packages/conditor/lib/corhal-fetch.js:99:57)
    at runMicrotasks (<anonymous>)
```

**Comment by parmentf** [comment]
I think the context you used `CORHALFetch` in was using [node-schedule](https://www.npmjs.com/package/node-schedule).
Be aware that
> Job objects are EventEmitters
